### ISSUE TITLE
Integrate the penguins use case with the middleware

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ICEBERG-middleware#22]

**Comment by AymenFJA** [comment]
Updating this ticket: 

The integration process of the `penguins` is in its final process. The code was committed [here](https://github.com/iceberg-project/ICEBERG-middleware/tree/feature/penguins) and is under testing. A pull request is coming soon if everything is working as expected.

**Comment by AymenFJA** [comment]
The integration process of the `penguins` is finished. The code will be tested and reviewed for the purpose of acceptance /rejection by the reviewers.
