### ISSUE TITLE
Generating session ID's error (unknown pattern in template)

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ICEBERG-middleware#27]
Hello All, 

During the integration process of the `penguins` use case with the middlewaree, i have faced the following error : 
```
Traceback (most recent call last):
  File "/home/aymen/iceberg/bin/iceberg", line 20, in <module>
    mode=ru.ID_PRIVATE, namespace='seals'),
  File "/home/aymen/iceberg/local/lib/python2.7/site-packages/radical/utils/ids.py", line 188, in generate_id
    return _generate_id(template, prefix, namespace)
  File "/home/aymen/iceberg/local/lib/python2.7/site-packages/radical/utils/ids.py", line 272, in _generate_id
    raise ValueError('unknown pattern in template (%s)' % template)
ValueError: unknown pattern in template (%(prefix)s.%(host)s.%(user)s.%(days)06d.%(day_counter)04d)
```

My environment information :
```
  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/aymen/iceberg

  radical.entk         : 0.72.0
  radical.pilot        : 0.73.1
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```

I have proposed a small fix under the `feature/penguins`  branch [here](https://github.com/iceberg-project/ICEBERG-middleware/blob/e5c970926b66869328e0c71b78eaa3e2ec2e52d2/bin/iceberg#L39) if that would be OK.

**Comment by bspitzbart** [comment]
Do you need:
exec_obj = Penguins(name = ru.generate_id('penguins.**search**', mode = ru.ID_PRIVATE, namespace = 'penguins'),
or more generally
exec_obj = Seals(name=ru.generate_id('penguins.%(item_counter)04d', mode=ru.ID_PRIVATE, namespace='penguins'),

Just a guess, based on seals.

**Comment by iparask** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check middleware issue by Aymen](https://trello.com/c/PI9ByVqQ/23-check-middleware-issue-by-aymen)

**Comment by iparask** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check middleware issue by Aymen](https://trello.com/c/PI9ByVqQ/23-check-middleware-issue-by-aymen)

**Comment by AymenFJA** [comment]
This is issue is solved.
