### ISSUE TITLE
Simplify argument parsing in ICEBERG command

### ISSUE THREAD

**Issue by iparask** [iceberg-project/ICEBERG-middleware#8]
Instead of having a complicated arg parsing mechanism, fully use arg parse capabilities for that.

**Proposal 1:** Reduce all arguments to a single level, regardless the use case. The command will be very close to what it is right now, but all arguments could be set. In the end based on the use case some may be use some not.

**Proposal 2:** Use argparse commands to specify the use case and as a result the rest of the parameters. it will look like:
```bash
iceberg usecase [<args>]
```
where use case will be one of the supported usecases.

What do you think is preferable?

[![](https://api.gh-polls.com/poll/01D812SWAMV9ZZP1F69PFX759A/Proposal1)](https://api.gh-polls.com/poll/01D812SWAMV9ZZP1F69PFX759A/Proposal1/vote)
[![](https://api.gh-polls.com/poll/01D812SWAMV9ZZP1F69PFX759A/Proposal2)](https://api.gh-polls.com/poll/01D812SWAMV9ZZP1F69PFX759A/Proposal2/vote)

**Comment by andre-merzky** [comment]
Note that argparse supports [subcommands](https://docs.python.org/2.7/library/argparse.html#sub-commands)

**Comment by iparask** [comment]
Arg parse commands it is then! Thank you @mturilli, @bspitzbart, @AymenFJA
